### ISSUE TITLE
Rayshud Installer crashes 

### ISSUE THREAD

**Issue by JaXjvJitchts** [CriticalFlaw/rayshud-Installer#13] opened 2019-04-16 12:29 UTC
So basically I installed rayshud installer and then opened up the program and got everything I wanted to customise in the rayshud installer, and after I set up the Dictionary part, I press Install and the program freezes and then later on crashes, can you please help me fix this problem ;-; would be greatly amazing

**Comment by CriticalFlaw** [comment] 2019-04-16 13:19
Thank you for reporting the issue. Which operating system are you using and does the app show any kind of error message before it crashes?

**Comment by CriticalFlaw** [comment] 2019-04-22 17:38
Alternatively you can also try version 2.3 which contains a logger, so when a crash happens you can just send me the log file so I can see what the issue is.

https://github.com/CriticalFlaw/rayshud-Installer/releases/tag/2.3

**Comment by Mati3219** [comment] 2019-06-02 18:05
My installer crashes too when I try to change color(for example:crosshair)
Also when I click "Install" it shows this: An error occurred while installing rays hud!
PS.I have windows 10 and i didn't extracted the rayshud_intaller.exe from the .zip
send help pls

**Comment by CriticalFlaw** [comment] 2019-06-02 18:17
I'm unable to replicate the crash on my side, so I would have to ask you to try version 2.3 (linked above) and send me the generated log so I can see why the application has crashed. Otherwise there isn't much I can do

**Comment by Mati3219** [comment] 2019-06-08 07:18
> I'm unable to replicate the crash on my side, so I would have to ask you to try version 2.3 (linked above) and send me the generated log so I can see why the application has crashed. Otherwise there isn't much I can do

Where can I find the generated log and how I am I going to send this?

**Comment by CriticalFlaw** [comment] 2019-06-08 12:26
The log file should be in the same place as the executable. Something like rayshud_installer.log you can upload it by dragging it into the text field here

**Comment by Mati3219** [comment] 2019-06-09 10:04
[rayshud_app.log](https://github.com/CriticalFlaw/rayshud-Installer/files/3269407/rayshud_app.log)




Is this it?

**Comment by CriticalFlaw** [comment] 2019-06-10 12:52
Yes, thank you. Is this from an instance where the installer crashed? It doesn't show any errors in the log.

**Comment by Mati3219** [comment] 2019-06-12 11:34
> Yes, thank you. Is this from an instance where the installer crashed? It doesn't show any errors in the log.

It doesn't crash anymore but it still says:
An error occurred while installing rays hud

**Comment by CriticalFlaw** [comment] 2019-06-12 11:43
The log is supposed to capture the exception message detailing what kind of error has occurred. The log you've sent says that the installation was completed successfully or is it from an instance when the error message was displayed? 

At least the crash has been fixed. So there's some good news.

**Comment by Mati3219** [comment] 2019-06-15 07:42
> The log is supposed to capture the exception message detailing what kind of error has occurred. The log you've sent says that the installation was completed successfully or is it from an instance when the error message was displayed?
> At least the crash has been fixed. So there's some good news.

What's an instance?
English isn't my first language :/

**Comment by CriticalFlaw** [comment] 2019-06-17 12:59
Send the log when you see the error message

> An error occurred while installing rayshud

appear again. The log should have a detailed explanation of why the error has occurred.

**Comment by CriticalFlaw** [comment] 2019-08-02 18:24
Crashes should be fixed in the upcoming version https://github.com/CriticalFlaw/rayshud-Installer/commit/d48c64c01f55f2756ae0e45c3cfd9e2d14828a97

**Closed by CriticalFlaw** 2019-08-02 18:24 UTC
Labels: bug report
